ignore:
  - "lib/app/screen"
  - "lib/app/widgets"
  - "lib/platform"

coverage:
  status:
    patch:
      default:
        target: 0
        threshold: -5
    project:
      default:
        target: 0
        threshold: -5
