name: collectio
description: A Flutter + Firebase application for collectors.

version: 1.0.0+2

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cloud_firestore: ^0.13.4+2
  cupertino_icons: ^0.1.2
  dartz: ^0.8.9
  equatable: ^1.1.1
  exif: ^1.0.3
  firebase_analytics: ^5.0.11
  firebase_auth: ^0.15.5+3
  firebase_storage: ^3.1.5
  flutter_bloc: ^4.0.0
  flutter_platform_widgets: ^0.51.0
  get_it: ^4.0.1
  google_maps_flutter: ^0.5.28+1
  http: ^0.12.1
  image_cropper: ^1.2.1
  image_picker: 0.6.5+3
  injectable: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^5.1.0
  build_runner: ^1.8.0
  injectable_generator: ^0.3.3
  mockito: ^4.1.1
  network_image_mock: ^1.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/i18n/
    - assets/images/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
