on: push
name: Lint & Test
jobs:
  build:
    name: Lint and Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
          flutter-version: "1.17.5"
      - uses: stelynx/dart-full-coverage@v1.0.5
        with:
          package: collectio
          ignore: "*_event.dart, *_state.dart"
      - run: flutter pub get
      - run: flutter packages pub run build_runner build
      - run: sed -i'.bak' -e 's@package:http/src/client.dart@package:http/http.dart@g' lib/util/injection/injection.iconfig.dart
      - run: sed -i'.bak' -e 's@package:in_app_purchase/src/in_app_purchase/in_app_purchase_connection.dart@package:in_app_purchase/in_app_purchase.dart@g' lib/util/injection/injection.iconfig.dart
      - run: flutter analyze
      - run: flutter test --coverage .
      - uses: codecov/codecov-action@v1.0.2
        with:
          token: ${{secrets.CODECOV_TOKEN}}
